server:
  port: ${PORT:8081}

spring:
  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: 123456
    hikari:
      maximum-pool-size: 3

  jpa:
    hibernate:
      ddl-auto: create-drop   # ou update (para não recriar sempre)
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgresql
