INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (101, 'COMIC BOOKS');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (102, 'COMIC BOOKS');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (103, 'COMIC BOOKS');

INSERT INTO SUPPLIER (ID, NAME) VALUES (101,'PANINI COMICS');
INSERT INTO SUPPLIER (ID, NAME) VALUES (102,'AMAZZON');

INSERT INTO PRODUCTO (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (101,'CRISE NAS TERRAS INFINITAS', 101, 101,110);
INSERT INTO PRODUCTO (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (102,'INTERESTELAR', 102, 102, 105);
INSERT INTO PRODUCTO (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (103,'WALKIN DEAD', 102, 102,105);